### ISSUE TITLE
Use Discord avatars dynamically

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RiiTag#12]
So the feature with RiiTag to use your avatar from Discord - it works, but the avatars are stored in `data/avatars` and never update when someone changes their avatar on Discord.

Could we work out a way to make the avatars be updated?

Maybe every time the RiiTag reboots, it clears out the avatar folder?

**Comment by bendevnull** [comment]
You're the one who forgot to implement this. Clear it out like the cache folder is cleared. Or, you could run a comparison against the saved avatar when the avatar is requested.

**Comment by bendevnull** [comment]
Fixed in PR #16
