### ISSUE TITLE
Blank cover displayed on tag

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RiiTag#13]
Here's something I noticed on some people's RiiTags - there's an empty space in between some covers. I think there's supposed to be a cover there, but I guess it shows up as a blank space when it can't find the cover?

Other tags that existed would display a "No Image" cover when it was missing, and then on the bottom of the cover show the game ID, but since I thought it didn't look good on the tag I removed functionality of that nature.

Also, I think the problem might be how Canvas creates new PNG instances and draws the cover image it downloaded into them.

**Comment by bendevnull** [comment]
That is the issue, and that's why the No Image cover existed. Theoretically, the drawing of a cover can be skipped with a return before any values are incremented, but I'd have to look over the source and see if that is indeed the case.

**Comment by bendevnull** [comment]
I'm unable to reproduce the issue in the latest commit of the Master branch.

Closing until steps on reproduction can be provided.
