### ISSUE TITLE
Make a Wii Channel forwarder for RiiTag

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RiiTag#15]
Here's a cool idea that was done with DUTag (a gamertag that doesn't work anymore) - someone made a forwarder WAD for the Internet Channel that just opened up your tag on the Internet Channel.

I like the idea, and the WAD is [here](https://drive.google.com/file/d/1GgW7Xbl5OSboi1MFZlhf8YCuLP6h6baj/view?usp=sharing), me or someone else could edit it so it has the RiiTag logo instead. You're able to view the RiiTag in the Internet Channel since I have it so you can use http as well as https.

You have to have the DOL in the WAD replaced to point to the URL, but [apparently ModMii can do it](https://i.imgur.com/n6FfvGG.png)?

In the end we can have a tutorial to create your own WAD to see your RiiTag.

**Comment by larsenv** [comment]
Maybe I can revisit this idea. This is probably one of the easiest things to implement on the list of issues.

iirc, Ben wasn't too excited about this idea and thought we should send the tag over Wii Mail when it updates, which won't work well, plus images the Wii receives will be really grainy.

**Comment by noahpistilli** [comment]
> Maybe I can revisit this idea. This is probably one of the easiest things to implement on the list of issues.
> 
> iirc, Ben wasn't too excited about this idea and thought we should send the tag over Wii Mail when it updates, which won't work well, plus images the Wii receives will be really grainy.

I can whip this up for you tonight if you want, libogc makes this super easy

**Comment by bendevnull** [comment]
Did you get around to working on it? I'm curious, even though skeptical

**Comment by larsenv** [comment]
Yes, I made the forwarder. I just need to figure out some way we can get a patcher working so someone can download a WAD of the forwarder, patched with their tag URL.

**Comment by larsenv** [comment]
Implemented in c9c8901f860c70ea35476548a8aece9a50fc14c1
