### ISSUE TITLE
Handle Wii VC injects for Wii U

### ISSUE THREAD

**Issue by Brawl345** [RiiConnect24/RiiTag#34]
I'm currently updating the Wii U plugin (see https://github.com/RiiConnect24/UTag/pull/3). Wii U games work flawlessly, but Wii VC injects aren't working. I currently send the whole TitleID (e.g. 0005000252535050 which is a Wii Sports inject). The last 8 numbers (52535050) are the ID4 of the title (RSPP).
RiiTag only seems to support ID6 for Wii games, so one has to enter RSPP01 - this won't work for VC injects.

Covers are downloaded from GameTDB, but it doesn't support ID4... How should we proceed? Is it even possible?

**Comment by TheShadowEevee** [comment]
It should be possible I think, considering there is [similar implementation for Wii U TitleIDs](https://github.com/RiiConnect24/RiiTag/blob/master/data/ids/wiiu.json) already; that list can be appended to or another list created to take the TitleID, Ex. `0005000252535050`, and manually change it to be, for example, `RSPP01` like you mentioned. A list of Wii games and their TitleID's would need to be made but it should be possible.

I feel like the question would be "Is this the best way to implement this", and "Who's going to make the list" considering this. I'm not sure if UTag passes the full TitleID or the ID4/ID6, so this solution may need to be implemented in UTag depending, although I think based on the other existing file RiiTag is the right place currently.

**Comment by TheShadowEevee** [comment]
This should be fixed/implemented in d1a76d4. Let me know if there are any issues.

RiiTag should now be able to take a TID like 0005000252535050 from above and translate it into the proper ID4-6 needed for use by RiiTag. This should mean little work to support anything new on the UTag side once the commit is pulled to the server.

**Comment by Brawl345** [comment]
Thank you! Is this already live? I'm sending a request to
```
http://tag.rc24.xyz/wiiu?game=0005000252535050&key=mykey
```
but it shows `wiiu-undefined;` on my RiiTag page

**Comment by TheShadowEevee** [comment]
It should be live now, it never got pulled to the server before apparently. It should work now.

**Comment by Brawl345** [comment]
Works now, thanks!
