### ISSUE TITLE
RiiTag in priiloader or something similar?

### ISSUE THREAD

**Issue by TheTechRobo** [RiiConnect24/RiiTag#48]
Copied from Discord:

> **TheTechRobo** <sup>Aujourd'hui à 11:42</sup> 
> &emsp;Sorry if this is a stupid question, could RiiTag ever be added to priiloader or something like that? I.e. when a channel [including the Disc Channel] is launched it'll contact the RiiTag Servers? I don't use USB loaders, I prefer discs.

**Comment by larsenv** [comment]
It's not currently a thing, but I'm sure it could be possible.
